# Generated by Django 4.1.7 on 2023-03-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('modified_at',)},
        ),
    ]
